//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace PG2024.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Auditoria
    {
        public int AuditoriaID { get; set; }
        public Nullable<int> UsuarioID { get; set; }
        public Nullable<System.DateTime> Fecha { get; set; }
        public string Accion { get; set; }
        public string TablaAfectada { get; set; }
        public string Detalles { get; set; }
    
        public virtual Usuario Usuario { get; set; }
    }
}
